name: Generate ascii artwork

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: install cowsay package
              run: sudo apt-get install cowsay -y

            - name: execute cowsay cmd
              run: cowsay -f dragon "run for cover" >> dragon.txt

            - name: read files and list files
              run: |
                ls -ltra
                cat dragon.txt


