name: my-first-workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: Read and list files
          run: |
            echo "welcome  to my first workflow"
            ls -ltra
            cat README.md

        - name: Generate ASCII artwork
          run: cowsay -f dragon "run for cover " >> dragon.txt

        # - name: list files
        #   run: ls

        # - name: read files
        #   run: cat README.md