name: my-first-workflow

on: push

jobs:
    build-job-1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: install cowsay package
          run: sudo apt-get install cowsay -y

        - name: Generate ASCII artwork
          run: cowsay -f dragon "run for cover, dragon is comming " >> dragon.txt

        - name: upload the file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-file
            path: dragon.txt
          

    test-job-2:
        needs: build-job-1
        runs-on: ubuntu-latest
        steps:
        - name: download the file
          uses: actions/download-artifact@v2
          with:
            name: dragon-file
        
        - name: list the files
          run: ls -ltra

    deploy-job-3:
        needs: test-job-2
        runs-on: ubuntu-latest
        steps:
        - name: upload the file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-file
            path: dragon.txt
            
        - name: read files 
          run: cat dragon.txt