name: my-first-workflow

on: push

jobs:
    build-job-1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: install cowsay package
          run: sudo apt-get install cowsay -y

        - name: Generate ASCII artwork
          run: cowsay -f dragon "run for cover, dragon is comming " >> dragon.txt

    test-job-2:
        runs-on: ubuntu-latest
        steps:
        - name: list the files
          run: ls -ltra

    deploy-job-3:
        runs-on: ubuntu-latest
        steps:
        - name: read files 
          run: cat dragon.txt