name: matric configuration

on: push

jobs:
    ubuntu-windows:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, windows-latest]
                images: [hello-world, alpine]
                exclude:
                  - os: windows-latest
                    images: alpine
                include:
                  - os: ubuntu-latest
                    images: amd64/alpine
        runs-on: ${{ matrix.os }}
        steps:
        - name: docker info
          run: docker info
      
        - name: run images on ${{ matrix.os }}
          run: docker run ${{ matrix.images }}

    # windows:
    #   runs-on: windows-latest
    #   steps:
    #   - name: docker info
    #     run: docker info
      
    #   - name: run images
    #     run: docker run hello-world