name: variable and secrets

on: push
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: my-image
  

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: docker build
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME

      - name: docker login
        run: echo docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: docker run
        run: echo docker run ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME