name: exploring filters in workflows

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - '!feature/*'   # ignore feature branches
    # branches-ignore:
    #   - feature/*
    #   - feature/**

  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
      - '**.md'
    branches:
      - main



jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo "hello world"